In [1]:
!pip install IPython 
from IPython.display import Image

# ISL 3.5

<img src = "img/KakaoTalk_20210717_102103567.png" height="50%" width="50%">


# ESL 3.4

<img src = "img/KakaoTalk_20210717_102120239.png" height="50%" width="50%">

# Coding

In [2]:
import numpy as np
import pandas as pd
import random
import math

In [3]:
df = pd.read_csv("Auto.csv")

In [4]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [5]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

In [6]:
df = df.drop(['origin','name'],axis=1)

In [7]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year
0  18.0          8         307.0        130    3504          12.0    70
1  15.0          8         350.0        165    3693          11.5    70
2  18.0          8         318.0        150    3436          11.0    70
3  16.0          8         304.0        150    3433          12.0    70
4  17.0          8         302.0        140    3449          10.5    70

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           397 non-null    float64
 1   cylinders     397 non-null    int64  
 2   displacement  397 non-null    float64
 3   horsepower    397 non-null    object 
 4   weight        397 non-null    int64  
 5   acceleration  397 non-null    float64
 6   year          397 non-null    int64  
dtypes: float64(3), int64(3), object(1)
memory usage: 21.8+ KB


In [9]:
for i in df.columns:
    print(df[i].isnull().value_counts())

False    397
Name: mpg, dtype: int64
False    397
Name: cylinders, dtype: int64
False    397
Name: displacement, dtype: int64
False    397
Name: horsepower, dtype: int64
False    397
Name: weight, dtype: int64
False    397
Name: acceleration, dtype: int64
False    397
Name: year, dtype: int64


In [10]:
df.corr()

mpg  cylinders  displacement    weight  acceleration  \
mpg           1.000000  -0.776260     -0.804443 -0.831739      0.422297   
cylinders    -0.776260   1.000000      0.950920  0.897017     -0.504061   
displacement -0.804443   0.950920      1.000000  0.933104     -0.544162   
weight       -0.831739   0.897017      0.933104  1.000000     -0.419502   
acceleration  0.422297  -0.504061     -0.544162 -0.419502      1.000000   
year          0.581469  -0.346717     -0.369804 -0.307900      0.282901   

                  year  
mpg           0.581469  
cylinders    -0.346717  
displacement -0.369804  
weight       -0.307900  
acceleration  0.282901  
year          1.000000

# Linear Regression

In [11]:
x = df[['cylinders','displacement','weight','acceleration','year']].to_numpy()
y = df['mpg'].to_numpy()

In [12]:
def normal_equation(X, Y):
    beta = np.dot((np.linalg.inv(np.dot(X.T,X))), np.dot(X.T,Y))

    return beta

In [13]:
beta = normal_equation(x,y)

In [14]:
beta

array([-0.49639433,  0.00769003, -0.00694174,  0.02978748,  0.59107344])

In [15]:
y_hat = np.dot(x,beta)

In [16]:
x

array([[   8. ,  307. , 3504. ,   12. ,   70. ],
       [   8. ,  350. , 3693. ,   11.5,   70. ],
       [   8. ,  318. , 3436. ,   11. ,   70. ],
       ...,
       [   4. ,  135. , 2295. ,   11.6,   82. ],
       [   4. ,  120. , 2625. ,   18.6,   82. ],
       [   4. ,  119. , 2720. ,   19.4,   82. ]])

In [17]:
beta

array([-0.49639433,  0.00769003, -0.00694174,  0.02978748,  0.59107344])

In [18]:
y_hat

array([15.79842565, 14.8022147 , 16.32526663, 16.26821893, 16.09708986,
       10.86679973, 10.93902036, 11.10801921, 10.4836345 , 13.93060059,
       15.91373029, 15.20416422, 14.65510299, 19.77862112, 24.23954696,
       20.71516337, 21.13241591, 22.45310461, 25.78151327, 28.00805072,
       22.20842429, 23.77589228, 24.22398019, 25.18455828, 21.99218111,
        8.55330162,  9.8345929 ,  9.83285157,  7.44452041, 26.37258671,
       25.80285255, 25.80044314, 27.09742634, 22.87463484, 17.30717458,
       18.26301641, 18.45044333, 18.40920715, 11.82624528, 10.42570985,
       12.26041209, 12.39436822,  6.88658623,  8.48303359,  5.74798899,
       20.81257937, 24.9074985 , 18.57438434, 19.55215908, 25.92518729,
       26.55239566, 26.77184089, 26.7545894 , 28.78488995, 29.87347051,
       28.56138468, 27.71997548, 26.08911091, 27.0697408 , 26.37097197,
       25.51346568, 26.54907899, 11.96610578, 11.5800743 , 12.72960763,
       13.01013523, 15.77639679, 10.05174671, 10.42807082, 10.74

In [19]:
len(y_hat)

397

## 알고보니 horsepower 변수에 ? 가 5개 있었음

In [20]:
sum(df['horsepower'] == '?')

5

In [21]:
df1 = df[df['horsepower']!='?']

In [22]:
df1

mpg  cylinders  displacement horsepower  weight  acceleration  year
0    18.0          8         307.0        130    3504          12.0    70
1    15.0          8         350.0        165    3693          11.5    70
2    18.0          8         318.0        150    3436          11.0    70
3    16.0          8         304.0        150    3433          12.0    70
4    17.0          8         302.0        140    3449          10.5    70
..    ...        ...           ...        ...     ...           ...   ...
392  27.0          4         140.0         86    2790          15.6    82
393  44.0          4          97.0         52    2130          24.6    82
394  32.0          4         135.0         84    2295          11.6    82
395  28.0          4         120.0         79    2625          18.6    82
396  31.0          4         119.0         82    2720          19.4    82

[392 rows x 7 columns]

In [23]:
x1 = df1[['cylinders','displacement','weight','acceleration','year']].to_numpy()
y1 = df1['mpg'].to_numpy()

In [24]:
beta1 = normal_equation(x1,y1)
beta1

array([-0.51578135,  0.00757069, -0.00685936,  0.03240177,  0.58887515])

In [25]:
y_hat1 = np.dot(x1,beta)
y_hat1

array([15.79842565, 14.8022147 , 16.32526663, 16.26821893, 16.09708986,
       10.86679973, 10.93902036, 11.10801921, 10.4836345 , 13.93060059,
       15.91373029, 15.20416422, 14.65510299, 19.77862112, 24.23954696,
       20.71516337, 21.13241591, 22.45310461, 25.78151327, 28.00805072,
       22.20842429, 23.77589228, 24.22398019, 25.18455828, 21.99218111,
        8.55330162,  9.8345929 ,  9.83285157,  7.44452041, 26.37258671,
       25.80285255, 25.80044314, 22.87463484, 17.30717458, 18.26301641,
       18.45044333, 18.40920715, 11.82624528, 10.42570985, 12.26041209,
       12.39436822,  6.88658623,  8.48303359,  5.74798899, 20.81257937,
       24.9074985 , 18.57438434, 19.55215908, 25.92518729, 26.55239566,
       26.77184089, 26.7545894 , 28.78488995, 29.87347051, 28.56138468,
       27.71997548, 26.08911091, 27.0697408 , 26.37097197, 25.51346568,
       26.54907899, 11.96610578, 11.5800743 , 12.72960763, 13.01013523,
       15.77639679, 10.05174671, 10.42807082, 10.74739075, 11.33

In [26]:
len(y_hat1)

392

계수랑 y_hat이 약간 바뀜